### ISSUE TITLE
个人信息页

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#13]
1红色*代表必填，不填点击下一页不能翻页（如果条件允许，可以在某一项未填写却点击下一页时弹出“请填写您的XXX”）；
2性别为选择题，点击即可；
318岁前主要居住城市需填写省市区（县），如果条件允许，可以设置下拉箭头，点击箭头，滑动选择地区，如果不可以，则请设置为三个填空题，直接手动输入地区。
![个人信息](https://user-images.githubusercontent.com/54254808/63639476-028b0400-c6c6-11e9-9a29-a38ce8d93111.png)

**Comment by lmxhappy** [comment]
这都是必填，那么不需要带星号了呗

**Comment by liuningyu** [comment]
可以不带星号 只需要保证信息不填完整不能翻到下一页就好

**Comment by lmxhappy** [comment]
已经修复，请check。谢谢

**Comment by liuningyu** [comment]
1邮箱后面“We'll never share your email with anyone else.”这句话能否改成“本次测试不会把您的个人信息泄露给他人”呢。
2本页面的呈现现在是居中的吗？我这边看是在左上角呈现的。

**Comment by lmxhappy** [comment]
我建议将这句话删除吧。有比邮箱更敏感的信息都有了。不差这个了。对于2，是另外一个最后的优化点，建议不要放到该页面的优化了。

**Comment by liuningyu** [comment]
好的老师 那信息页没什么问题了  我关掉了哈
