### ISSUE TITLE
Bug——按钮问题

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#15]
1第一页欢迎页的按钮“下一页”点击一次不换页，必须点击两次
![欢迎](https://user-images.githubusercontent.com/54254808/63661889-db7c2180-c7ee-11e9-8d35-dc4d1d50995b.png)
2知情同意页的“否”按钮，点击后是回到上一页，但是这时候再点击第一页的下一页，会到的却不是知情同意页
![知情同意](https://user-images.githubusercontent.com/54254808/63661933-1aaa7280-c7ef-11e9-9059-52eb593a6ae3.png)
3填写信息的“上一页”按钮，是去下一页的，不能返回上一页
![填写信息](https://user-images.githubusercontent.com/54254808/63662006-6bba6680-c7ef-11e9-803f-ae2fb05af299.png)
4快速读字表指导语点击开始按钮会弹出一个对话框
![字表16](https://user-images.githubusercontent.com/54254808/63662091-cc49a380-c7ef-11e9-9ed1-a904ffa47c6e.png)
第一个快速朗读句子指导语页的开始键也要点两次才进入下一页（您设置了两次快速朗读句子指导语，请删除一个）
![朗读句子](https://user-images.githubusercontent.com/54254808/63664940-a0ccb600-c7fb-11e9-83e9-09eb4c8e51b4.png)

**Comment by lmxhappy** [comment]
已经解决了。请check。谢谢

**Comment by liuningyu** [comment]
检查无误 马上关闭
