### ISSUE TITLE
优化——点击问题

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#16]
1快速读数、读图、读字表测试请设置在时间到后点击会变绿色，上一版点击是会变绿的，这一版点击后只有一次快速读数是变绿的，其他的都直接跳到了下一页。

**Comment by lmxhappy** [comment]
https://github.com/lmxhappy/psych_h5test/issues/7
在这里写的是，点击到下一页。
现在就是这样的哦。

**Comment by liuningyu** [comment]
麻烦把这个修改成点击到的数、图、字会变绿色，持续一秒，然后再跳到下一页，谢谢。

**Comment by lmxhappy** [comment]
该issue与issue7目的一样，建议合并。并check。
