### ISSUE TITLE
Bug——句子重复

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#17]
快速默读测试中“牛顿发明了点灯”出现了两次

**Comment by lmxhappy** [comment]
朗读中也发现了重复的问题。连同以上的问题一并解决了。请check。

**Comment by liuningyu** [comment]
嗯嗯 好的老师！晚点我check一下！




| |
ljx1573699@126.com
邮箱：nyny0207@163.com
|

Signature is customized by Netease Mail Master

在2019年09月13日 17:08，lmxhappy 写道：

朗读中也发现了重复的问题。连同以上的问题一并解决了。请check。
