### ISSUE TITLE
Bug——点击循环问题

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#18]
朗读测试最后的两个评估问题点击确定后一直在循环，跳不到最后一页了。

**Comment by lmxhappy** [comment]
这个已经解决了吧？

**Comment by liuningyu** [comment]
已解决 现在关掉它

**Comment by liuningyu** [comment]
已解决 现在关掉它

**Comment by liuningyu** [comment]
已解决 现在关掉它

**Comment by liuningyu** [comment]
嗯嗯 已解决 已关掉




| |
ljx1573699@126.com
邮箱：nyny0207@163.com
|

Signature is customized by Netease Mail Master

在2019年09月13日 17:00，lmxhappy 写道：

这个已经解决了吧？
