### ISSUE TITLE
部分Bug——流程混乱

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#19]
1朗读句子指导语后面应该出现的是两个句子练习，但是这里直接出现了评估题目
![image](https://user-images.githubusercontent.com/54254808/63737622-a8529480-c8b9-11e9-94ea-607213fe47bc.png)
![image](https://user-images.githubusercontent.com/54254808/63737628-abe61b80-c8b9-11e9-90c9-cad3dac15a4a.png)
2快速朗读句子指导语出现两次，请删掉一个
3第二个快速朗读句子指导语后面没显示句子页面，直接出了判断对错页面，需加入要读的练习句子。
![image](https://user-images.githubusercontent.com/54254808/63737722-f1a2e400-c8b9-11e9-9431-f5fed82d5bc5.png)
![image](https://user-images.githubusercontent.com/54254808/63737709-ea7bd600-c8b9-11e9-86a5-c5b56022d747.png)
4练习句子应该有两对（四屏），既读句子1——判断对错——读句子2——判断对错，现在只有一屏判断对错，需要补上三屏。
![image](https://user-images.githubusercontent.com/54254808/63738031-07fd6f80-c8bb-11e9-809a-9b9a38f95486.png)

**Comment by lmxhappy** [comment]
请check哈。并根据check结果，更新issue。谢谢

**Comment by liuningyu** [comment]
> 请check哈。并根据check结果，更新issue。谢谢
两个评估题的循环问题已解决。
