### ISSUE TITLE
Bug——朗读句子缺少一个练习

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#20]
朗读句子指导语后面应该呈现练习句子：土豆是黄色的
就是在以下两屏中间插入 土豆是黄色的  读完
![b619f1870f6053a7319b7c6d528dbf7](https://user-images.githubusercontent.com/54254808/64868892-ca4a6600-d672-11e9-9be3-70f173593601.png)
![6b848332f34a540c0688d3d5d49ddf6](https://user-images.githubusercontent.com/54254808/64868895-ccacc000-d672-11e9-8b5a-4bcb52a0f9e6.png)

**Comment by lmxhappy** [comment]
已解决。请check。

**Comment by liuningyu** [comment]
老师，默读句子和朗读句子都缺少第一个练习句子的呈现（指导语后直接出现了对错号）；
默读句子正式实验呈现的所有句子都一样，就是一个句子呈现了很多次。

辛苦老师啦！

**Comment by lmxhappy** [comment]
第一个貌似没有问题，发你微信了
第二个是bug，已经fix。

**Comment by liuningyu** [comment]
默读句子正式测试部分没有问题了，默读句子和朗读句子的练习部分缺少题目，麻烦老师再给看下，谢谢老师。

**Comment by liuningyu** [comment]
已解决！谢谢老师啦！
