### ISSUE TITLE
Bug——字表朗读一材料不呈现

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#21]
老师，字表朗读测试一指导语后面没有呈现字表材料，只呈现了大约30秒的空屏。

**Comment by lmxhappy** [comment]
已经解决，请check

**Comment by liuningyu** [comment]
老师，我从https://github.com/lmxhappy/psych_h5test下载最新的，是只有句子朗读的测试，暂时找不到字表测试，请问这个要去哪里下载呢？
谢谢老师！




| |
ljx1573699@126.com
邮箱：nyny0207@163.com
|

Signature is customized by Netease Mail Master

在2019年09月28日 21:25，lmxhappy 写道：

已经解决，请check

**Comment by lmxhappy** [comment]
刚才出了点问题，请再check。

**Comment by liuningyu** [comment]
已解决，谢谢老师！
马上关闭
