### ISSUE TITLE
优化——字表测试点击多个汉字变色

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#22]
字表测试需要在十五秒内让被试点击声母为“W”的字，在点击这些字的时候是不跳页的，但是希望这十五秒内点击到的字能变一下色（如果可以的话能否设定为红色字或红色框，并一直保持红色）。
十五秒后，出现“时间到，请点击您最后读到的汉字”，这时候被试点击他最后读到的汉字，才会变色并跳页（如果可以的话请设定为绿色，绿方框或绿色字都可以）。
![image](https://user-images.githubusercontent.com/54254808/64910393-875ac200-d748-11e9-998b-e87afaa2e270.png)

在前几个版本的测试中，有点击多个汉字都变绿但不跳页的设置，近两版没有了呢。

**Comment by lmxhappy** [comment]
已经解决，请check

**Comment by liuningyu** [comment]
已解决！谢谢老师！
