### ISSUE TITLE
线上优化——位置需调整

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#24]
1填写信息页的“提交”按钮，可不可以放在右下角呢，就跟“下一页”按钮位置差不多；
![微信图片_20191006094237](https://user-images.githubusercontent.com/54254808/66263003-0316ce80-e81e-11e9-9550-34fa4a252e42.png)
2句子测试位置能否上调一点，居中显示（如果是我手机显示的问题，那这条就算了哈）
![微信图片_20191006094253](https://user-images.githubusercontent.com/54254808/66263009-33f70380-e81e-11e9-93f6-c5aabb06b9b5.png)
3评估题目的选项下面的确认按钮横屏是看不见的，老师您那边可以显示吗？
![微信图片_20191006094259](https://user-images.githubusercontent.com/54254808/66263015-5ee15780-e81e-11e9-92e0-e4a94ed45ddc.png)

**Comment by lmxhappy** [comment]
done.请check

**Comment by liuningyu** [comment]
1信息页按钮位置已更改√
2老师，句子默读测试的句子已经在中间了，但是句子朗读测试的句子还是有点偏下（这个也是安卓用户那边看已经居中了，苹果用户看还是偏下，是因为手机屏幕太小了吗）？谢谢老师。

**Comment by lmxhappy** [comment]
2与另一个issue重复了把
