### ISSUE TITLE
线上优化——Bug

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#25]
评估问题点击选项后会出现这个对话框，麻烦老师去掉下，谢谢。
![微信图片_20191006094256](https://user-images.githubusercontent.com/54254808/66263024-a536b680-e81e-11e9-8044-89061688f638.png)

**Comment by lmxhappy** [comment]
done

**Comment by liuningyu** [comment]
老师，这个不知道是不是手机的问题，有几个安卓系统的同学说，这个对话框已经不出现了，但是苹果用户在做的时候还是出现了这个。

**Comment by lmxhappy** [comment]
再请他们试一下。谢谢

**Comment by liuningyu** [comment]
问题已解决，谢谢老师。
