### ISSUE TITLE
线上优化——横屏指示

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#26]
老师，我刚在做测试的时候，发现咱们在开始没有讲明白需要将手机解除屏幕锁定，横屏进行测试，咱们可以在第一页这个空白位置加“请解除手机屏幕方向锁定，旋转手机进行横屏测试”这句话吗？
![微信图片_20191006100504](https://user-images.githubusercontent.com/54254808/66263176-d7491800-e820-11e9-8ee9-e8fae94ba932.jpg)

**Comment by lmxhappy** [comment]
横屏这个事，在其它页面已经提及了，请全面评估一下，作出一个合适的方案。
