### ISSUE TITLE
线上优化——图片显示

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#27]
读图指导语中小图片不显示，麻烦老师给调整下，谢谢老师！
![微信图片_20191006100847](https://user-images.githubusercontent.com/54254808/66263213-4d4d7f00-e821-11e9-9d81-ca306ecac370.png)

**Comment by lmxhappy** [comment]
done

**Comment by lmxhappy** [comment]
段落也是都是乱的。我调整了一下。

**Comment by liuningyu** [comment]
无误，谢谢老师。
