### ISSUE TITLE
线上优化——位置调整

### ISSUE THREAD

**Issue by liuningyu** [lmxhappy/psych_h5test#30]
老师，两次字表测试中“时间到，请点击您最后读到的汉字”这句话麻烦调到中间位置，谢谢老师。
![微信图片_20191007083156](https://user-images.githubusercontent.com/54254808/66278567-f907d500-e8dc-11e9-8a84-db97b693b95e.jpg)
![微信图片_20191007083201](https://user-images.githubusercontent.com/54254808/66278568-f907d500-e8dc-11e9-92c9-2cf0bb085ed1.jpg)

**Comment by lmxhappy** [comment]
done
